# Generated by Django 6.0.7 on 2026-08-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(help_text='000000#', max_length=20, verbose_name='کد رنگ'),
        ),
    ]
